/// Flutter icons Steak
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Steak
///      fonts:
///       - asset: fonts/Steak.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class Steak {
  Steak._();

  static const _kFontFam = 'Steak';
  static const String? _kFontPkg = null;

  static const IconData meat = IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
